CPTAC:
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/coad_cptac_2019_clinical_data.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/coad_cptac_2019_slide.csv
  feature_dir:
    raw:
      retccl: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Raw/RetCCL/
      ctranspath: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Raw/CPTAC_HistAuGAN_CTransPath/
    histaugan:
      ctranspath: /lustre/groups/peng/datasets/histology_data/CPTAC/features/Raw/CPTAC_HistAuGAN_CTransPath/

TCGA-CRC:
  clini_table: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-CRC-DX_CLINI.xlsx
  slide_csv: /lustre/groups/peng/datasets/histology_data/clini_tables/TCGA-CRC-DX_SLIDE.csv
  slide_dir: /lustre/groups/shared/histology_data/TCGA/CRC/slides
  feature_dir:
    raw:
      ctranspath: /lustre/groups/peng/datasets/histology_data/TCGA-CRC/features/marugoto_histaugan/
      custom: /lustre/groups/peng/workspace/sophia.wagner/logs/dinov2/vim_w-layernorm_w-ckpt_w-abs-pos-emb_wo-rope/model_0037499.rank_0.pth
  folds: /lustre/groups/shared/histology_data/TCGA/CRC/folds

TCGA-BRCA:
  clini_table: /lustre/groups/shared/histology_data/TCGA/annotations/tcga_brca_clini.csv
  slide_csv: /lustre/groups/shared/histology_data/TCGA/annotations/tcga_brca_slide.csv
  slide_dir: /lustre/groups/shared/histology_data/TCGA/BRCA/slides
  feature_dir:
    raw:
      custom: /lustre/groups/shared/histology_data/TCGA/BRCA/features/0512_px_20_mag_otsu
  folds: /lustre/groups/shared/histology_data/TCGA/BRCA/folds

TCGA-NSCLC:
  clini_table: /lustre/groups/shared/histology_data/TCGA/annotations/tcga_lung_clini.csv
  slide_csv: /lustre/groups/shared/histology_data/TCGA/annotations/tcga_lung_slide.csv
  slide_dir: /lustre/groups/shared/histology_data/TCGA/NSCLC/slides
  feature_dir:
    raw:
      custom: /lustre/groups/shared/histology_data/TCGA/NSCLC/features/0512_px_20_mag_otsu
  folds: /lustre/groups/shared/histology_data/TCGA/NSCLC/folds
