# logging options
project: dino_eval_slide-level

# task definition
data_config: dinov2/eval/slide_level/data_config.yaml
task: binary
target: subtype
num_classes: 1
cohorts: ['TCGA-NSCLC']
ext_cohorts: []  # add CPTAC cohort here
clini_info: {}
seed: null
label_dict:
  0: 0
  1: 1

# model options
model: AttentionMIL
model_config: {}
  # dropout: 0.2
  # heads: 4
  # dim_head: 64
  # dim: 256
  # mlp_dim: 256
norm: raw
num_tiles: -1
pad_tiles: false

# training options
folds: 5
num_epochs: 10
criterion:  BCEWithLogitsLoss 
optimizer: AdamW
lr_scheduler: 'OneCycleLR'
lr_scheduler_config:
  max_lr: 1.0e-04
#   T_max: 10
# lr_scheduler_warmup: null # 'LinearLR'
# lr_scheduler_warmup_config: {}
#   start_factor: 0.033
#   total_iters: 2
lr: 2.0e-05
wd: 2.0e-05
bs: 1
stop_criterion: loss
val_check_interval: 500
num_samples: null
